Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -15,21 +15,32 @@ pipeline {
     stages {
         stage('Detect Configuration Drift') {
             steps {
-                sh '''
-                    terraform init
-                    terraform plan -detailed-exitcode -out=tfplan
-                '''
-                 script {
-                    def exitCode = sh(
-                        returnStatus: true,
-                        script: 'echo $?'
-                    )
-                    if (exitCode == 2) {
-                        error "Configuration drift detected! Run 'terraform apply' to update the infrastructure."
-                    } else if (exitCode == 1) {
-                        error "There was an error running 'terraform plan'. Check the logs for details."
-                    } else {
-                        echo "No configuration drift detected."
+                script {
+                    def repos = [
+                        [name: 'repo1', statefile: 's3://demo-bucket-terraform1000/terraformDemoDay0/tfstate.tfstate'],
+                        [name: 'repo2', statefile: 's3://demo-bucket-terraform1000/terraformDemoDayN_Drift/tfstate.tfstate'],
+                        [name: 'repo3', statefile: 's3://demo-bucket-terraform1000/terraformDemoDay0_deleteDemo/tfstate.tfstate']
+                    ]
+                    for (def repo in repos) {
+                        sh '''
+                            terraform init \
+                                -backend-config="bucket=${repo.statefile}"
+                            terraform plan \
+                                -detailed-exitcode \
+                                -out=tfplan \
+                                -var="state_file=${repo.statefile}"
+                        '''
+                        def exitCode = sh(
+                            returnStatus: true,
+                            script: 'echo $?'
+                        ).trim().toInteger()
+                        if (exitCode == 2) {
+                            error "Configuration drift detected in ${repo.name}! Run 'terraform apply' to update the infrastructure."
+                        } else if (exitCode == 1) {
+                            error "There was an error running 'terraform plan' in ${repo.name}. Check the logs for details."
+                        } else {
+                            echo "No configuration drift detected in ${repo.name}."
+                        }
                     }
                 }
             }
